#!/usr/bin/env bash

function error_message () {
  echo
  echo "ERROR: $1"
  echo -e "\n usage: $(basename $0) file"
  echo -e "\nParameters:"
  echo -e "\t file  \t file to watch"
  exit 1
}

function check_program_available () {
  [[ ! `command -v $1` ]] && error_message "command not available: $1"
}

check_program_available "fswatch"

export file="$1"
full_path="$(pwd)/$file"
export mbin_rel="${full_path/*mbin\/}"

[[ -e "$file" ]] || (echo "file not found: $file" && exit 1)

function sync_file () {
  printf "$(date '+%T') rsync [$file]..."
  rsync "$file" $MEMORIA:~/bin/mbin/$mbin_rel
  printf "done\n"
}
export -f sync_file

sync_file
printf "watching $file...\n"
fswatch -0 -o "$file" | xargs -0 -n 1 bash -c sync_file