#!/usr/bin/env bash

function check_env () {
  if [ ! ${!1} ]; then
    echo "Environment variable '$1' not set!"
    exit
  fi
}

check_env MEMORIA

if [ $# -eq 0 ]; then
  echo "sshing into $MEMORIA"
  ssh $MEMORIA
  exit
fi

check_env MEMORIA_CUR
check_env MEMORIA_SER
check_env MEMORIA_MOV

case "$1" in
  "-c" )
    shift
    SOURCES="$@"
    TARGET="$MEMORIA:$MEMORIA_CUR"
  ;;
  "-s" )
    shift
    SOURCES="$@"
    TARGET="$MEMORIA:$MEMORIA_SER"
  ;;
  "-m" )
    shift
    SOURCES="$@"
    TARGET="$MEMORIA:$MEMORIA_MOV"
  ;;
  "-gs" )
    shift
    SOURCES="$MEMORIA:$MEMORIA_SER/$@"
    TARGET="."
  ;;
  "-gm" )
    shift
    SOURCES="$MEMORIA:$MEMORIA_MOV/$@"
    TARGET="."
  ;;
  "-h" | "--help" )
    echo -e "\n usage: $(basename -- $0) [ DIRECTION ] [ -R ] file"
    echo -e "\t DIRECTION options:"
    echo -e "\t\t -c  \t send to current (default)"
    echo -e "\t\t -s  \t send to series"
    echo -e "\t\t -m  \t send to movies"
    echo -e "\t\t -gs \t get series"
    echo -e "\t\t -gm \t get movies"
    echo -e "\t -R  \t use relative path names"
    exit
  ;;
  * )
    SOURCES="$@"
    TARGET="$MEMORIA:$MEMORIA_CUR"
  ;;
esac

echo "rsync from $SOURCES to $TARGET"
rsync --progress --partial -r \
  --perms --chmod=Du=rwx,Dgo=rx,Fa=rw \
  --exclude=".DS*" --exclude="~*" \
  "$SOURCES" "$TARGET"
