#!/usr/bin/env bash

function print_usage () {
  echo -e "\n usage: $(basename -- $0) [DIRECTION] [OPTIONS] file"
  echo -e "\nssh to $MEMORIA when no arguments given."
  echo "DIRECTION"
  echo -e "\t -c  \t send to current (default)"
  echo -e "\t -s  \t send to series"
  echo -e "\t -m  \t send to movies"
  echo -e "\t -gs \t get series"
  echo -e "\t -gm \t get movies"
  echo "OPTIONS"
  echo -e "\t -R  \t use relative path names"
  echo -e "\t -h  \t show this help"
}

function check_env () {
  if [ ! ${!1} ]; then
    echo "Environment variable '$1' not set!"
    exit
  fi
}

check_env MEMORIA

if [ $# -eq 0 ]; then
  echo "sshing into $MEMORIA"
  ssh "$MEMORIA"
  exit
fi

check_env MEMORIA_CUR
check_env MEMORIA_SER
check_env MEMORIA_MOV

PATH_ARGS=( "$@" )
USE_RELATIVE_PATHS=

function remove_first_path_arg () {
  PATH_ARGS=( "${PATH_ARGS[@]:1}" )
}

function check_for_relative_paths () {
  if [ "${PATH_ARGS[0]}" == "-R" ]; then
    USE_RELATIVE_PATHS=1
    remove_first_path_arg
  fi
}

case "${PATH_ARGS[0]}" in
  "-c" )
    remove_first_path_arg
    check_for_relative_paths
    SOURCES=( "${PATH_ARGS[@]}" )
    TARGET="$MEMORIA:$MEMORIA_CUR"
  ;;
  "-s" )
    remove_first_path_arg
    check_for_relative_paths
    SOURCES=( "${PATH_ARGS[@]}" )
    TARGET="$MEMORIA:$MEMORIA_SER"
  ;;
  "-m" )
    remove_first_path_arg
    check_for_relative_paths
    SOURCES=( "${PATH_ARGS[@]}" )
    TARGET="$MEMORIA:$MEMORIA_MOV"
  ;;
  "-gs" )
    remove_first_path_arg
    check_for_relative_paths
    SOURCES=( "$MEMORIA:$MEMORIA_SER/${PATH_ARGS[0]}" )
    TARGET="."
  ;;
  "-gm" )
    remove_first_path_arg
    check_for_relative_paths
    SOURCES=( "$MEMORIA:$MEMORIA_MOV/${PATH_ARGS[0]}" )
    TARGET="."
  ;;
  -[!R] )
    if [ "${PATH_ARGS[0]}" != "-h" ]; then
      echo "illegal option ${PATH_ARGS[0]}"
    fi
    print_usage
    exit
  ;;
  * ) # default option uses same path as -c
    check_for_relative_paths
    SOURCES=( "${PATH_ARGS[@]}" )
    TARGET="$MEMORIA:$MEMORIA_CUR"
  ;;
esac

echo "rsync ${SOURCES[@]%/} to $TARGET ${USE_RELATIVE_PATHS:+(using relative path names)}"
rsync --progress --partial -r ${USE_RELATIVE_PATHS:+-R} \
  --perms --chmod=Du=rwx,Dgo=rx,Fa=rw \
  --exclude=".DS*" --exclude="~*" \
  "${SOURCES[@]%/}" "$TARGET"
