#!/usr/bin/env bash

function error_message () {
  echo
  echo "ERROR: $1"
  echo -e "\n usage: $(basename $0) csv_file"
  echo -e "\nParameters:"
  echo -e "\t csv_file \t CSV file containing audio tracks to record"
  exit 1
}

function check_file_exists () {
  [[ ! -f "$1" ]] && error_message "$2"
}

function check_exit_code () {
  [[ $? -ne 0 ]] && error_message "processing failed: $1"
}

check_file_exists "$1" "No CSV file provided!"

function trim () {
  echo $1 | awk '{$1=$1};1'
}

while IFS=\; read -r link artist title
do
    link=`trim "${link}"`
    artist=`trim "${artist}"`
    title=`trim "${title}"`
    fname="${artist} - ${title}"
    tmp_file="${fname}.tmp"
    out_file="${fname}.mp3"

    echo "processing [${fname}] ..."
#    echo -e "[${artist}]\t\t[${title}]"
    exec_cmd="ffmpeg -v panic -stats -i {} -metadata artist=\"${artist}\" -metadata title=\"${title}\" \"${out_file}\" </dev/null && rm {}"
    youtube-dl -x -q -o "${tmp_file}" --exec "${exec_cmd}" "${link}"
    check_exit_code "youtube-dl ${link}"
done < "$1"
