#!/usr/bin/env bash

abort_with() {
  echo $1
  cmdName="$(basename -- $0)"
  echo -e "\nusage: $cmdName file title"
  echo -e "       $cmdName -auto extension     automatically sets default title in *.extension files"
  exit
}

replace_title() {
  if [ ! "$2" ]; then
   abort_with "Error: 2 parameters required"
  fi

  if [ ! -f "$1" ]; then
   abort_with "Error: Not a file: $1"
  fi

  TMP_FILE="$1.old"
  mv "$1" "$TMP_FILE"
  ffmpeg -i "$TMP_FILE" -stats -v 0 -c copy -metadata title="$2" "$1"
  rm "$TMP_FILE"
}

if [ "$1" == "-auto" ]; then
  echo "setting titles in all *.$2 files..."
  epDiv="S[0-9][0-9]E[0-9][0-9]"
  for infile in *.${2}; do
    if [ -f "$infile" ]; then
      title=$(echo "$infile" | sed "s/.*$epDiv.\(.*\)\.$2/\1/")
      serName=$(echo "$infile" | sed "s/\(.*\)\.$epDiv.*/\1/")
      epNum=$(echo "$infile" | sed "s/.*\($epDiv\).*/\1/")
      title="${serName//./ } ${epNum} ${title//./ }"
      echo "$infile <$title>"
      replace_title "$infile" "$title"
    fi
  done

else
  replace_title "$1" "$2"
fi
