#!/usr/bin/env bash

function print_usage_exit () {
  echo -e "\n usage: $(basename $0) sl[n]..."
  echo -e "\nSpaces in parameters are ignored."
  echo -e "\t s  \t short beep"
  echo -e "\t l  \t long beep"
  echo -e "\t n  \t pauses for n seconds"
  exit
}

function short_beep () {
  /sbin/pic_raw 80
  sleep 1
}

function long_beep () {
  /sbin/pic_raw 81
  sleep 2
}

function user_log () {
  [[ $SHLVL -le 2 ]] && printf "$1"
}

cmdlist="$*"
cmdlist="${cmdlist// /}"

if [[ ${cmdlist} =~ ([^ls0-9]) ]]; then
  echo "ERROR: unrecognised command: ${BASH_REMATCH[1]}"
  print_usage_exit
fi

while [[ $cmdlist ]]; do
  [[ $cmdlist =~ ([ls]|[0-9]*)(.*) ]]
  action="${BASH_REMATCH[1]}"
  cmdlist="${BASH_REMATCH[2]}"
  
  case $action in
    "l" )
      user_log "long beep... "
      long_beep
    ;;
    "s" )
      user_log "short beep... "
      short_beep
    ;;
    [0-9]* )
      user_log "pause $action secs... "
      sleep $action
    ;;
    * )
      echo "general error"
      print_usage_exit
    ;;
  esac
  user_log "done\n"
done

