#!/bin/bash

CONN_THRESHOLD=10
PNAME="node"

result=`ssh $MSMSSH /bin/bash --login 2>&1 << EOF
  open_connections -s $PNAME
EOF`

if [[ $? -ne 0 ]]; then
  timelog "ssh connection failed: $result"
  beep s1s1s1l1s1s1s1
  exit 1
fi

cnt="${result##*:}"
if [[ "$cnt" -ge "$CONN_THRESHOLD" ]]; then
  timelog "threshold exceeded: $cnt >= $CONN_THRESHOLD"
  beep l1l1s1s1s1l1l
  exit 1
fi

timelog "s'all good man"
