#!/usr/bin/env bash

CONN_THRESHOLD=$MSM_NODE_CONNS
PNAME="node"

result=`ssh -o ConnectTimeout=30 $MSMSSH /usr/bin/env bash -l << EOF
  open_connections -s $PNAME
EOF`
ssh_exit_code=$?

if [[ $ssh_exit_code -ne 0 ]]; then
  timelog "ssh connection failed: $result"
  beep s1s1s1l1s1s1s1
  exit 1
fi

cnt="${result##*:}"
if [[ "$cnt" -ge "$CONN_THRESHOLD" ]]; then
  timelog "threshold exceeded: $cnt >= $CONN_THRESHOLD"
  beep l1l1s1s1s1l1l
  exit 1
fi

timelog "s'all good man (${cnt} connections)"
