#!/usr/bin/env bash

function check_env () {
  if [[ ! ${!1} ]]; then
    timelog "Environment variable '$1' not set!"
    exit
  fi
}

CUSTOM_PROFILE="/share/MD0_DATA/Public/bin/.custom_profile"
source "$CUSTOM_PROFILE"
check_env PUBLIC
check_env USER_HOME
check_env LOGDIR

timelog "------ sym links"
function safelink {
  if [[ ! -e "$1" ]]; then
    timelog "Create link $1 to $2"
    ln -s "$2" "$1"
  else
    timelog "Link already exists: $1"
  fi
}

safelink "$USER_HOME/media" "$PUBLIC/media"
safelink "$USER_HOME/series" "$PUBLIC/media/series"
safelink "$USER_HOME/movies" "$PUBLIC/media/movies"
safelink "$USER_HOME/bin" "$PUBLIC/bin"
safelink "$USER_HOME/data" "$PUBLIC/data"
safelink "$USER_HOME/logs" "$LOGDIR"
safelink "$USER_HOME/public" "$PUBLIC"

timelog "------ .bash_profile appendices"
BRC="$USER_HOME/.bash_profile"

function appendLine {
  timelog "Adding \"$1\" to $BRC"
  echo "$1" >> "$BRC"
}

appendLine "##### restart setup appendices:"
appendLine "source $CUSTOM_PROFILE"
appendLine "export PS1=\"\\n\\[\\033[1;34m\\]\\u@\\h\\[\\033[00m\\] \\[\\033[0;32m\\]\\w\\[\\033[00m\\]\\n\\$ \""
appendLine "alias shutdown=\"halt\""
appendLine "alias hexit=\"halt; exit\""
appendLine "bind 'set mark-symlinked-directories on'"
