#!/bin/bash

PUBLIC="~/bin"

echo -e "\n ======================================"
echo " == env variables"
echo " ======================================"

BRC=~/.bash_profile

function appendEnv {
  ENV_KEY="$1"
  ENV_VAL="$2"
  NEW_LINE="export $ENV_KEY=$ENV_VAL"
  if grep -sq "^${NEW_LINE/ /\s}$" $BRC
  then
      echo "$ENV_KEY is already set."
  else
      echo "Adding \"$NEW_LINE\" to $BRC"
      echo -e "$NEW_LINE" >> $BRC
  fi
}

appendEnv "WEB_DIR" "/share/Web"
appendEnv "TMPDIR" "$PUBLIC/tmp"
MBIN="$PUBLIC/mbin/memoria"
appendEnv "MBIN" "$MBIN"
appendEnv "PATH" "/Apps/bin:\$PATH"
appendEnv "PATH" "\$MBIN:\$PATH"

echo -e "\n ======================================"
echo " == sym links"
echo " ======================================"

function linkdir {
  if [ ! -d "$1" ]; then
    echo "Create link to $2"
    ln -s $2 $1
  else
    echo "Link already exists: $1"
  fi
}

linkdir ~/media /share/Public/media
linkdir ~/bin /share/Public/bin
linkdir ~/mbin "$MBIN"

echo "export PS1=\"\\[\\033[1;34m\\]\\u@\\h\\[\\033[00m\\] \\[\\033[0;32m\\]\\w\\[\\033[00m\\] \\$ \"" >> $BRC

source $BRC
