#!/bin/bash

USER_HOME="/root"
PUBLIC="/share/MD0_DATA/Public"
BRC=$USER_HOME/.bash_profile

function appendLine {
  echo "Adding \"$1\" to $BRC"
  echo "$1" >> $BRC
}

echo -e "\n ======================================"
echo " == env variables"
echo " ======================================"

function appendEnv {
  ENV_KEY="$1"
  ENV_VAL="$2"
  NEW_LINE="export $ENV_KEY=$ENV_VAL"
  if grep -sq "^${NEW_LINE/ /\s}$" $BRC
  then
    echo "$ENV_KEY is already set."
  else
    appendLine "$NEW_LINE"
  fi
}

appendEnv "WEB_DIR" "/share/Web"
MBIN="$PUBLIC/bin/mbin/memoria"
appendEnv "MBIN" "$MBIN"
appendEnv "PATH" "/Apps/bin:\$PATH"
appendEnv "PATH" "\$MBIN:\$PATH"

echo -e "\n ======================================"
echo " == sym links"
echo " ======================================"

function savelink {
  if [ ! -d "$1" ]; then
    echo "Create link to $2"
    ln -s $2 $1
  else
    echo "Link already exists: $1"
  fi
}

savelink $USER_HOME/media $PUBLIC/media
savelink $USER_HOME/bin $PUBLIC/bin
savelink $USER_HOME/data $PUBLIC/data
savelink $MBIN/set_title $MBIN/../haumea/set_title

echo -e "\n ======================================"
echo " == line appendices"
echo " ======================================"

appendLine "export PS1=\"\\[\\033[1;34m\\]\\u@\\h\\[\\033[00m\\] \\[\\033[0;32m\\]\\w\\[\\033[00m\\] \\$ \""
appendLine "alias shutdown=\"halt\""
appendLine "bind 'set mark-symlinked-directories on'"
