#!/usr/bin/env bash

BACKUP_DIR="$BAKDIR/tantalus"
TMP_DIR="tmp"
BAK_FILE="tantalus_db_$(date +"%Y%m%d_%H%M").gz"

function exit_with () {
  exit_code="$1"
  timelog "done [$exit_code]"
  exit "$exit_code"
}

timelog "dumping remote db..."
ssh "$MSMSSH" /usr/bin/env bash << EOF
  cd "$TMP_DIR" &&
  mongodump --quiet --db=tantalus --excludeCollection=sessions --numParallelCollections=1 --gzip --archive="$BAK_FILE"
EOF
[ $? -ne 0 ] && exit_with 1

timelog "transferring dump file..."
rsync -q -P -r "$MSMSSH":"~/$TMP_DIR/$BAK_FILE" "$BACKUP_DIR"
[ $? -ne 0 ] && exit_with 2

timelog "cleanup..."
ssh "$MSMSSH" /usr/bin/env bash << EOF
  cd "$TMP_DIR" &&
  rm "$BAK_FILE"
EOF
[ $? -ne 0 ] && exit_with 3

exit_with 0
