#!/usr/bin/env bash

function print_usage () {
  echo -e "\n usage: $(basename $0) [ -h ] DIRECTION [OPTIONS] file"
  echo -e "\nssh to $MEMORIA when no arguments given."
  echo -e "\nParameters:"
  echo -e "   -h             show this help"
  echo -e "\nDIRECTION"
  echo -e "   -c             send to current (default)"
  echo -e "   -s             send to series"
  echo -e "   -m             send to movies"
  echo -e "   -x TARGET_DIR  send to \$HOME/TARGET_DIR"
  echo -e "   -gs            get series"
  echo -e "   -gm            get movies"
  echo -e "\nOPTIONS"
  echo -e "   -d             dry-run rsync command"
  echo -e "   -l             copy symlinks as symlinks"
  echo -e "   -p             only prints rsync command"
  echo -e "   -R             use relative path names"
}

function error_exit () {
  echo "$1"
  print_usage
  exit 1
}

function check_env () {
  if [[ ! ${!1} ]]; then
    echo "Environment variable '$1' not set!"
    exit
  fi
}

check_env MEMORIA

if [[ $# -eq 0 ]]; then
  echo "sshing into $MEMORIA"
  ssh "$MEMORIA"
  exit
fi

check_env MEMORIA_CUR
check_env MEMORIA_SER
check_env MEMORIA_MOV

PATH_ARGS=( "$@" )
USE_RELATIVE_PATHS=
DRY_RUN=
PRINT_ONLY=
COPY_SYMLINKS=

function remove_first_path_arg () {
  PATH_ARGS=( "${PATH_ARGS[@]:1}" )
}

function check_options () {
  remove_first_path_arg # remove DIRECTION parameter
  HAS_OPTION=true
  while [[ $HAS_OPTION == true ]]; do
    case "${PATH_ARGS[0]}" in
      "-d" )
        DRY_RUN=true
      ;;
      "-l" )
        COPY_SYMLINKS=true
      ;;
      "-p" )
        PRINT_ONLY=true
      ;;
      "-R" )
        USE_RELATIVE_PATHS=true
      ;;\
      -* )
        error_exit "OPTION invalid: ${PATH_ARGS[0]}"
      ;;
      * )
        HAS_OPTION=false
      ;;
    esac
    [[ $HAS_OPTION == true ]] && remove_first_path_arg
  done
}

case "${PATH_ARGS[0]}" in
  "-c" )
    check_options
    SOURCES=( "${PATH_ARGS[@]}" )
    TARGET="$MEMORIA:$MEMORIA_CUR"
  ;;
  "-s" )
    check_options
    SOURCES=( "${PATH_ARGS[@]}" )
    TARGET="$MEMORIA:$MEMORIA_SER"
  ;;
  "-m" )
    check_options
    SOURCES=( "${PATH_ARGS[@]}" )
    TARGET="$MEMORIA:$MEMORIA_MOV"
  ;;
  "-x" )
    remove_first_path_arg
    TARGET_DIR="${PATH_ARGS[0]}"
    if [[ "$TARGET_DIR" =~ ^-.* ]]; then
      error_exit "TARGET_DIR invalid: $TARGET_DIR"
    fi
    check_options
    SOURCES=( "${PATH_ARGS[@]}" )
    TARGET="$MEMORIA:~/$TARGET_DIR"
  ;;
  "-gs" )
    check_options
    SOURCES=( "$MEMORIA:$MEMORIA_SER/${PATH_ARGS[0]}" )
    TARGET="."
  ;;
  "-gm" )
    check_options
    SOURCES=( "$MEMORIA:$MEMORIA_MOV/${PATH_ARGS[0]}" )
    TARGET="."
  ;;
  * )
    if [[ "${PATH_ARGS[0]}" != "-h" ]]; then
      error_exit "DIRECTION invalid: ${PATH_ARGS[0]}"
    fi
    print_usage
    exit
  ;;
esac

echo "rsync ${SOURCES[@]%/} to $TARGET ${USE_RELATIVE_PATHS:+(using relative path names)}"
if [[ $PRINT_ONLY ]]; then
  echo "==== PRINT ONLY ===="
  echo "rsync --progress --partial -t -r \
    ${USE_RELATIVE_PATHS:+-R} ${DRY_RUN:+-n} ${COPY_SYMLINKS:+-l} \
    --perms --chmod=Du=rwx,Dgo=rx,Fa=rw \
    --exclude=\"~*\" --exclude=\".*\" \
    ${SOURCES[@]%/} $TARGET"
else
  rsync --progress --partial -t -r \
    ${USE_RELATIVE_PATHS:+-R} ${DRY_RUN:+-n} ${COPY_SYMLINKS:+-l} \
    --perms --chmod=Du=rwx,Dgo=rx,Fa=rw \
    --exclude="~*" --exclude=".*" \
    "${SOURCES[@]%/}" "$TARGET"
fi
