#!/bin/bash

if [ -z "$1" ]; then
  echo "Missing program parameter!"
  exit
fi

# check if sleep supports <1secs:
sleep .1 2> /dev/null
[[ $? -eq 0 ]] && delay=".3" || delay="1"

while [ true ]; do 
  res=`lsof -i tcp -n | grep "$1" | wc -l`
  echo -e "conn #: $res \033[1A"
  sleep $delay
done
