#!/usr/bin/env bash

out_file_ext="mp4"

function error_message () {
  echo -e "ERROR: $1"
  echo -e "\n usage: $(basename $0) [ -d ] csv"
  echo -e "\nParameters:"
  echo -e "  -d  \t dry run"
  echo -e "  csv \t CSV file containing video tracks to record"
  exit 1
}

function file_not_found () {
  ! [[ -f "$1" ]] && echo 1
}

function check_exit_code () {
  exit_code=$?
  if [[ $exit_code -ne 0 ]]; then
    echo "processing failed: $1"
    echo "exit code: $exit_code"
    exit 1
  fi
}

function safe_name () {
  name=`trim_str "$1"`
  echo "${name// /.}"
}

DRY_RUN=false
if [[ $1 == "-d" ]]; then
  DRY_RUN=true
  echo -e "${FG_LIGHT_MAGENTA}========== DRY RUN ============"
  shift
fi
CSV_FILE="$1"

if [[ $(file_not_found "$CSV_FILE") ]]; then
  error_message "No CSV file provided!"
fi

missing_files=()
printf "finding missing files...\033[s"
missing_count=0
while IFS=\; read show season episode title link; do
  if [[ "${show}${season}${episode}${title}${link}" ]]; then
    show=`safe_name "${show}"`
    season=`trim_str "${season}"`
    episode=`trim_str "${episode}"`
    title=`safe_name "${title}"`
    link=`trim_str "${link}"`
    fname="${show}.${season}${episode:+$episode.}${title}.${out_file_ext}"

    if [[ $(file_not_found "$fname") ]]; then
      if [[ "$link" =~ (.*_)([0-9]*)(\.ts.*) ]]; then
        url="${BASH_REMATCH[1]}XXX${BASH_REMATCH[3]}"
        pieces="${BASH_REMATCH[2]}"
      else
        error_message "File: [$fname]\nCannot extract URL template from link: [$link]"
      fi
      missing_files+=( "$show;$season;$episode;$title;$fname;$url;$pieces" )
      let missing_count=missing_count+1
      printf "\033[u $missing_count"
    fi
  fi
done < "$CSV_FILE"

if [[ $missing_count == 0 ]]; then
  echo "all files available."
  exit
fi

echo -e "\n pieces\t file "
for miss in "${missing_files[@]}"; do
  miss=`echo "$miss" | cut -f 5,7 -d ';'`
  pieces=${miss#*;}
  fname=${miss%;*}
  echo -e " ${pieces} \t ${fname}"
done

request_confirmation "continue?"
if [[ $? != 0 ]]; then
  echo "abort."
  exit
fi

for miss in "${missing_files[@]}"; do
  IFS=';' read show season episode title fname url count <<< "$miss"

  if $DRY_RUN; then
    echo "record_ts" "${url}" ${count} ${fname}
  else
    record_ts "${url}" ${count} ${fname}
    check_exit_code "record_ts"
    rm -rf delete_me
    set_title ${fname} "${season}${episode} ${title//./ }"
    check_exit_code "set_title"
  fi
done
