#!/usr/bin/env bash

abort_with() {
  echo -e "ERROR: $1"
  cmdName="$(basename $0)"
  echo -e "\nusage: $cmdName file title"
  echo -e "          sets title in file"
  echo -e "   or: $cmdName -auto [ -d ] [ -s ] ext"
  echo -e "          sets default titles in all \"*.ext\" files in current directory"
  echo -e "               -d   dry-run"
  echo -e "               -s   use a smaller title format"
  exit
}

COL_GREEN="\033[92m"
COL_RED="\033[91m"
COL_DEFAULT="\033[39m"

replace_title() {
  if [[ ! "$2" ]]; then
   abort_with "2 parameters required"
  fi

  if [[ ! -f "$1" ]]; then
   abort_with "Not a file: $1"
  fi

  TMP_FILE="$1.old"
  mv "$1" "$TMP_FILE"
  ffmpeg -i "$TMP_FILE" -stats -v 0 -c copy -metadata title="$2" "$1"
  rm "$TMP_FILE"
}

dry_run_message() {
  echo -e "================= ${COL_RED} DRY-RUN ${COL_DEFAULT} ================="
}

if [[ "$1" == "-auto" ]]; then
  if [[ "$2" == "-d" ]]; then
    dry_run_message
    DRYRUN=1
    shift
  fi
  if [[ "$2" == "-s" ]]; then
    SMALL_FMT=1
    shift
  fi

  echo "setting titles in all *.$2 files..."
  epDiv="S[0-9][0-9]E[0-9][0-9]"
  for infile in *.${2}; do
    if [[ -f "$infile" ]]; then
      title=$(echo "$infile" | sed "s/.*$epDiv.\(.*\)\.$2/\1/")
      epNum=$(echo "$infile" | sed "s/.*\($epDiv\).*/\1/")
      title="${epNum} ${title//./ }"

      if [[ -z $SMALL_FMT ]]; then
        serName=$(echo "$infile" | sed "s/\(.*\)\.$epDiv.*/\1/")
        title="${serName//./ } ${title}"
      fi

      echo -e "$infile <${COL_GREEN}${title}${COL_DEFAULT}>"
      if [[ -z $DRYRUN ]]; then
         replace_title "$infile" "$title"
      fi
    fi
  done

  if [[ $DRYRUN ]]; then
    dry_run_message
  fi
else
  replace_title "$1" "$2"
fi

exit 0
