#!/usr/bin/env bash

abort_with() {
  echo -e "ERROR: $1"
  cmdName="$(basename $0)"
  echo -e "\nusage: $cmdName file title"
  echo -e "          sets title in file"
  echo -e "   or: $cmdName -auto [ -d ] [ -s ] ext"
  echo -e "          sets default titles in all \"*.ext\" files in current directory"
  echo -e "               -d   dry-run"
  echo -e "               -s   use a smaller title format"
  exit
}

COL_GREEN="\033[92m"
COL_RED="\033[91m"
COL_DEFAULT="\033[39m"

replace_title() {
  origin_file="$1"
  tmp_file="$origin_file.old"
  new_title="$2"
  if [[ ! "$new_title" ]]; then
   abort_with "2 parameters required"
  fi

  if [[ ! -f "$origin_file" ]]; then
   abort_with "Not a file: $origin_file"
  fi

  mv "$origin_file" "$tmp_file"
  ffmpeg -i "$tmp_file" -stats -v 0 -c copy -metadata title="$new_title" "$origin_file"
  if [[ $? -eq 0 ]]; then
    rm "$tmp_file"
  else
    printf "ffmpeg error, restoring file... "
    mv "$tmp_file" "$origin_file"
    printf "done\n"
    exit 1
  fi
}

dry_run_message() {
  echo -e "================= ${COL_RED} DRY-RUN ${COL_DEFAULT} ================="
}

if [[ "$1" == "-auto" ]]; then
  if [[ "$2" == "-d" ]]; then
    dry_run_message
    DRYRUN=1
    shift
  fi
  if [[ "$2" == "-s" ]]; then
    SMALL_FMT=1
    shift
  fi

  echo "setting titles in all *.$2 files..."
  input_files=()
  while read line; do
    input_files+=("$line")
  done < <(find . -type f -name "*.${2}")

  epDiv="S[0-9][0-9]E[0-9][0-9]"
  for infile in "${input_files[@]}"; do
    title=$(echo "$infile" | sed "s/.*$epDiv.\(.*\)\.$2/\1/")
    epNum=$(echo "$infile" | sed "s/.*\($epDiv\).*/\1/")
    title="${epNum} ${title//./ }"

    if [[ -z $SMALL_FMT ]]; then
      serName=$(echo "${infile/*\/}" | sed "s/\(.*\)\.$epDiv.*/\1/")
      title="${serName//./ } ${title}"
    fi

    echo -e "$infile <${COL_GREEN}${title}${COL_DEFAULT}>"
    if [[ -z $DRYRUN ]]; then
       replace_title "$infile" "$title"
    fi
  done

  if [[ $DRYRUN ]]; then
    dry_run_message
  fi
else
  replace_title "$1" "$2"
fi

exit 0
