#!/usr/bin/env bash

function formatLog () {
  echo -e "[$(date '+%Y-%m-%d %H:%M:%S')]: $*"
}


if [[ -z "$1" ]]; then
  while IFS= read -r line
  do
    formatLog "$line"
  done < "${1:-/dev/stdin}"
else
  formatLog "$*"
fi

