#!/usr/bin/env bash
echo $1 | awk '{$1=$1};1'

#$(echo -e "${FOO}" | tr -d '[:space:]')
#echo "$1" | sed -e 's/^[\w]*//' -e 's/[\W]*$//'
#echo "${tmp//['\t\r\n ']^}"


#tmp=${1%%*( )}
#tr '^\n' ' ' <<< "$1"
#tmp=`echo "${1//^[$'\t\r\n ']*}"`
#echo "${tmp}"